### ISSUE TITLE
Blogpost on si4703: unfitting sentence

### ISSUE THREAD

**Issue by dwagenk** [eldruin/eldruin.github.io#1]
There's a sentence in your newest blog post, that doesn't seem to fit. It's between the `cargo.toml` excerpt and the example programs code block.
> Here is an example program which will measure the ambient light in lux (source):
I can't relate it to your post at all.

**Comment by eldruin** [comment]
Oops sorry about that. That's a left over from another post.
Should be fixed now. Thank you for the hint!
